"""add outbox.

Revision: 3f76f2fb1e22
Revises: e20721479cb8
Creation Date: 2026-04-01 01:33:26.611607

"""  # noqa: N999

import typing

import sqlalchemy
from alembic import op as alembic_operations


revision: typing.Final = "3f76f2fb1e22"
down_revision: typing.Final = "e20721479cb8"
branch_labels: typing.Final = None
depends_on: typing.Final = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic_operations.create_table(
        "outbox",
        sqlalchemy.Column("id", sqlalchemy.Uuid(), nullable=False),
        sqlalchemy.Column("event_type", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column("aggregate_id", sqlalchemy.Uuid(), nullable=False),
        sqlalchemy.Column("aggregate_type", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column("payload", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("occurred_on_utc", sqlalchemy.DateTime(timezone=True), nullable=False),
        sqlalchemy.Column("processed_on_utc", sqlalchemy.DateTime(timezone=True), nullable=True),
        sqlalchemy.Column(
            "publishing_datetime", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("changed_by", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "changed_at", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("is_deleted", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic_operations.drop_table("outbox")
    # ### end Alembic commands ###
