"""init.

Revision: e20721479cb8
Revises:
Creation Date: 2026-03-16 14:57:56.336657

"""  # noqa: N999

import typing

import sqlalchemy
from alembic import op as alembic_operations


revision: typing.Final = "e20721479cb8"
down_revision: typing.Final = None
branch_labels: typing.Final = None
depends_on: typing.Final = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic_operations.create_table(
        "couriers",
        sqlalchemy.Column("id", sqlalchemy.Uuid(), nullable=False),
        sqlalchemy.Column("name", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column("speed", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("location_x", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("location_y", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column(
            "publishing_datetime", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("changed_by", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "changed_at", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("is_deleted", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    alembic_operations.create_table(
        "orders",
        sqlalchemy.Column("id", sqlalchemy.Uuid(), nullable=False),
        sqlalchemy.Column("location_x", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("location_y", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("volume", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("status", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column("courier_id", sqlalchemy.Uuid(), nullable=True),
        sqlalchemy.Column(
            "publishing_datetime", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("changed_by", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "changed_at", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("is_deleted", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    alembic_operations.create_table(
        "storage_places",
        sqlalchemy.Column("id", sqlalchemy.Uuid(), nullable=False),
        sqlalchemy.Column("courier_id", sqlalchemy.Uuid(), nullable=False),
        sqlalchemy.Column("name", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column("total_volume", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("order_id", sqlalchemy.Uuid(), nullable=True),
        sqlalchemy.Column(
            "publishing_datetime", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("changed_by", sqlalchemy.String(), nullable=True),
        sqlalchemy.Column(
            "changed_at", sqlalchemy.DateTime(), server_default=sqlalchemy.text("CURRENT_DATE"), nullable=True
        ),
        sqlalchemy.Column("is_deleted", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.ForeignKeyConstraint(["courier_id"], ["couriers.id"], ondelete="CASCADE"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic_operations.drop_table("storage_places")
    alembic_operations.drop_table("orders")
    alembic_operations.drop_table("couriers")
    # ### end Alembic commands ###
